// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Gauge.CSharp.Runner")]
[assembly: GuidAttribute("b80cc90b-dd04-445b-825e-51a42f3cadaf")]
[assembly: AssemblyDescriptionAttribute("C# spec for Gauge. http://getgauge.io")]
[assembly: AssemblyVersionAttribute("0.8.0")]
[assembly: AssemblyFileVersionAttribute("0.8.0")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("Gauge.CSharp.Core")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(true)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.0";
        internal const string InformationalVersion = "0.8.0";
    }
}
