// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Gauge.CSharp.Core")]
[assembly: GuidAttribute("db098a05-ce23-4b6d-a124-4d125bc89f57")]
[assembly: AssemblyDescriptionAttribute("[INTERNAL GAUGE USE ONLY] Communicate with Gauge Core")]
[assembly: AssemblyVersionAttribute("0.0.11")]
[assembly: AssemblyFileVersionAttribute("0.0.11")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("Gauge.CSharp.Core")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(true)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Gauge.CSharp.Core";
        internal const System.String Guid = "db098a05-ce23-4b6d-a124-4d125bc89f57";
        internal const System.String AssemblyDescription = "[INTERNAL GAUGE USE ONLY] Communicate with Gauge Core";
        internal const System.String AssemblyVersion = "0.0.11";
        internal const System.String AssemblyFileVersion = "0.0.11";
        internal const System.String AssemblyConfiguration = "";
        internal const System.String AssemblyCompany = "ThoughtWorks Inc.";
        internal const System.String AssemblyProduct = "Gauge.CSharp.Core";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyTrademark = "";
        internal const System.String AssemblyCulture = "";
        internal const System.Boolean ComVisible = true;
    }
}
