// <auto-generated/>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Gauge.CSharp.Core")]
[assembly: Guid("db098a05-ce23-4b6d-a124-4d125bc89f57")]
[assembly: AssemblyDescription("[INTERNAL GAUGE USE ONLY] Communicate with Gauge Core")]
[assembly: AssemblyVersion("0.2.2")]
[assembly: AssemblyFileVersion("0.2.2")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("ThoughtWorks Inc.")]
[assembly: AssemblyProduct("Gauge.CSharp.Core")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(true)]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyTitle = "Gauge.CSharp.Core";
        internal const string Guid = "db098a05-ce23-4b6d-a124-4d125bc89f57";
        internal const string AssemblyDescription = "[INTERNAL GAUGE USE ONLY] Communicate with Gauge Core";
        internal const string AssemblyVersion = "0.2.2";
        internal const string AssemblyFileVersion = "0.2.2";
        internal const string AssemblyConfiguration = "";
        internal const string AssemblyCompany = "ThoughtWorks Inc.";
        internal const string AssemblyProduct = "Gauge.CSharp.Core";
        internal const string AssemblyCopyright = "Copyright ©  2016";
        internal const string AssemblyTrademark = "";
        internal const string AssemblyCulture = "";
        internal const bool ComVisible = true;
    }
}