// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Gauge.CSharp.Core")]
[assembly: GuidAttribute("db098a05-ce23-4b6d-a124-4d125bc89f57")]
[assembly: AssemblyDescriptionAttribute("[INTERNAL GAUGE USE ONLY] Communicate with Gauge Core")]
[assembly: AssemblyVersionAttribute("0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.3")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("Gauge.CSharp.Core")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(true)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.3";
        internal const string InformationalVersion = "0.0.3";
    }
}
