// <auto-generated/>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Gauge.CSharp.Lib")]
[assembly: Guid("21677428-1b2a-4a9b-9865-f72209fb8f1c")]
[assembly: AssemblyDescription("C# support for Gauge. http://getgauge.io")]
[assembly: AssemblyVersion("0.6.2")]
[assembly: AssemblyFileVersion("0.6.2")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("ThoughtWorks Inc.")]
[assembly: AssemblyProduct("Gauge.CSharp.Core")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(true)]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyTitle = "Gauge.CSharp.Lib";
        internal const string Guid = "21677428-1b2a-4a9b-9865-f72209fb8f1c";
        internal const string AssemblyDescription = "C# support for Gauge. http://getgauge.io";
        internal const string AssemblyVersion = "0.6.2";
        internal const string AssemblyFileVersion = "0.6.2";
        internal const string AssemblyConfiguration = "";
        internal const string AssemblyCompany = "ThoughtWorks Inc.";
        internal const string AssemblyProduct = "Gauge.CSharp.Core";
        internal const string AssemblyCopyright = "Copyright ©  2016";
        internal const string AssemblyTrademark = "";
        internal const string AssemblyCulture = "";
        internal const bool ComVisible = true;
    }
}