// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Gauge.CSharp.Lib")]
[assembly: GuidAttribute("21677428-1b2a-4a9b-9865-f72209fb8f1c")]
[assembly: AssemblyDescriptionAttribute("C# support for Gauge. http://getgauge.io")]
[assembly: AssemblyVersionAttribute("0.5.3")]
[assembly: AssemblyFileVersionAttribute("0.5.3")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("Gauge.CSharp.Core")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(true)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.3";
        internal const string InformationalVersion = "0.5.3";
    }
}
